<?php
    echo $this->getChildHtml('somethingdigital_criteo_device_detection');
?>

<script type="text/javascript">
    window.criteo_q = window.criteo_q || [];
    window.criteo_q.push(
        { event: "setAccount", account: "<?php echo Mage::getStoreConfig('somethingdigital_criteo/settings/account_number'); ?>" },
        { event: "setHashedEmail", email: ["<?php echo Mage::helper('somethingdigital_criteo')->getHashedEmail();?>"] },
        { event: "setSiteType", type: deviceType },
        { event: "viewHome" }
    );
</script>