<?php
    echo $this->getChildHtml('somethingdigital_criteo_device_detection');
    $email = Mage::helper('somethingdigital_criteo')->getHashedEmail();
    $items = $this->getCriteoViewList();
    $useDataLayer = Mage::getStoreConfig('somethingdigital_criteo/settings/use_datalayer');
?>

<?php if (!$useDataLayer): ?>
    <script type="text/javascript">
        window.criteo_q = window.criteo_q || [];
        window.criteo_q.push(
            { event: "setAccount", account: "<?php echo Mage::getStoreConfig('somethingdigital_criteo/settings/account_number'); ?>" },
            { event: "setHashedEmail", email: ["<?php echo $email?>"] },
            { event: "setSiteType", type: deviceType },
            { event: "viewList", item: <?php echo $items; ?>, keywords: "<?php echo $this->getCriteoSearchKeywords(); ?>" }
        );
    </script>
<?php else: ?>
    <script type="text/javascript">
        var dataLayer = dataLayer || [];
        dataLayer.push(
            {
                event: "crto_listingpage",
                crto: {
                    email: "<?php echo $email; ?>",
                    products: <?php echo $items ?>
                }
            }
        );
    </script>
<?php endif; ?>
