<script type="text/javascript"> 
    window.criteo_q = window.criteo_q || []; 
    window.criteo_q.push(
        { event: "setAccount", account: "<?php echo Mage::getStoreConfig('somethingdigital_criteo/settings/account_number'); ?>" },
        { event: "setHashedEmail", email: ["<?php echo Mage::helper('somethingdigital_criteo')->getHashedEmail();?>"] },
        { event: "setSiteType", type: "d" },
        { event: "viewList", item: <?php echo $this->getCriteoViewList(); ?>, keywords: "<?php echo $this->getCriteoSearchKeywords(); ?>" }
    ); 
</script>