<?php
    echo $this->getChildHtml('somethingdigital_criteo_device_detection');
    $email = Mage::helper('somethingdigital_criteo')->getHashedEmail();
    $orderId = $this->getData('order_id');
    $items = $this->getCriteoOrderItems();
    $useDataLayer = Mage::getStoreConfig('somethingdigital_criteo/settings/use_datalayer');
?>

<?php if (!$useDataLayer): ?>
    <script type="text/javascript">
        window.criteo_q = window.criteo_q || [];
        window.criteo_q.push(
            { event: "setAccount", account: "<?php echo Mage::getStoreConfig('somethingdigital_criteo/settings/account_number'); ?>" },
            { event: "setHashedEmail", email: ["<?php echo Mage::helper('somethingdigital_criteo')->getHashedEmail();?>"] },
            { event: "setSiteType", type: deviceType },
            { event: "trackTransaction",
                <?php if (Mage::getStoreConfigFlag('somethingdigital_criteo/settings/use_deduplication')): ?>
                    deduplication: (Mage.Cookies.get('criteo_deduplication')) ? 1 : 0,
                <?php endif; ?>
                id: "<?php echo $orderId ?>",
                new_customer: <?php echo $this->getCriteoIsNewCustomer(); ?>,
                item: <?php echo $items ?>
            }
        );
    </script>
<?php else: ?>
    <script type="text/javascript">
        var dataLayer = dataLayer || [];
        dataLayer.push(
            {
                event: "crto_transactionpage",
                crto: {
                    email: "<?php echo $email; ?>",
                    transactionid: "<?php echo $orderId ?>",
                    products: <?php echo $items ?>
                }
            }
        );
    </script>
<?php endif;  ?>
